[workspace]
members = [
  "crates/support",
  "crates/configuration",
  "crates/orchestrator",
  "crates/provider",
  "crates/test-runner"
]

[workspace.dependencies]
thiserror = "1.0"
async-trait = "0.1"
futures = "0.3"
serde = { verson="1.0" }
serde_json = "1.0"
tokio = "1.28"
