[package]
name = "provider"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
futures = "0.3.28"
napi = { version="2.12.7", features=["async"]}
napi-derive = "2.12.5"
serde = {verson="1.0.163", features = ["derive"]}
serde_json = "1.0.96"
