name: Cargo Build & Test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Zombienet SDK - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Clippy
        run: cargo clippy --all-targets --all-features
      - name: Build
        run: cargo build --verbose
      - name: Tests
        run: cargo test --verbose