name: Cargo Create Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    name: Zombienet SDK - Docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v3

      - name: Init nigthly install for fmt
        run: rustup update nightly && rustup default nightly && rustup component add rustfmt

      - name: Check format
        run: cargo +nightly fmt --check --all

      - name: Init install
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy

      - name: Create Docs
        run: cargo doc --no-deps

      - name: Run script for copying docs
        run: ./doc_preparation.sh
        