name: Spellcheck

on:
  push:
    branches:
      - tw-spellcheck-action
  pull_request:
    branches:
      - tw-spellcheck-action

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-spellcheck
        run: cargo install cargo-spellcheck

      - name: Run cargo-spellcheck
        run: cargo spellcheck
